[project]
name = "litewebapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "pymongo>=4.12.1",
    "uvicorn[standard]>=0.34.2",
]
